version: '3.7'

services:
  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: nexus
    expose:
      - 8081
      - 8082
      - 8083
    ports:
      - "8991:8081"
      - "8992:8082"
      - "8993:8083"
    volumes:
      - ./nexus-data:/nexus-data
